[[GAP_pkg_deepthought]]
arch = "aarch64"
git-tree-sha1 = "b2d4f20411678cc301e569748028bec4daedde46"
os = "macos"

    [[GAP_pkg_deepthought.download]]
    sha256 = "8ba372d663fd8c3e5b5d2140465047deb08ba1012980cd88c52760f2e68475b2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v100.0.700+0/GAP_pkg_deepthought.v100.0.700.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_deepthought]]
arch = "aarch64"
git-tree-sha1 = "6207fc5a2e70120af048b95233b89ff3379fb339"
libc = "glibc"
os = "linux"

    [[GAP_pkg_deepthought.download]]
    sha256 = "4d3540f07e513ca3a129eb5e441ea1b31ddaf6c4ee943643d75125357d390c4b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v100.0.700+0/GAP_pkg_deepthought.v100.0.700.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_deepthought]]
arch = "aarch64"
git-tree-sha1 = "3a81e81ec9f37627ef9e472f00ff8a58f908b23f"
libc = "musl"
os = "linux"

    [[GAP_pkg_deepthought.download]]
    sha256 = "411af0912ecef6abd841f939a7a15575f73eff3830708e528b51d98030407467"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v100.0.700+0/GAP_pkg_deepthought.v100.0.700.aarch64-linux-musl.tar.gz"
[[GAP_pkg_deepthought]]
arch = "powerpc64le"
git-tree-sha1 = "4fcad6fa137654eadbafc789a44081a042c908a0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_deepthought.download]]
    sha256 = "0e6358c86aa28e349f486e4d4ff1303c8d566ff8cb4b3b2ae1ae068340c619a4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v100.0.700+0/GAP_pkg_deepthought.v100.0.700.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_deepthought]]
arch = "x86_64"
git-tree-sha1 = "0397742835bb7413c223d4f1f32dbaea87a54ef5"
os = "macos"

    [[GAP_pkg_deepthought.download]]
    sha256 = "e836c25c049fdba5bcd456a483e200601eaed268fcd92bb51d47a237e1ab6ef6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v100.0.700+0/GAP_pkg_deepthought.v100.0.700.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_deepthought]]
arch = "x86_64"
git-tree-sha1 = "42f566773fa232d8c6987046ad2da08b122fcfcb"
libc = "glibc"
os = "linux"

    [[GAP_pkg_deepthought.download]]
    sha256 = "035694a38174e35d376113a5856854e5bbf2fc3caab9a36bddf788f6dc464fa8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v100.0.700+0/GAP_pkg_deepthought.v100.0.700.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_deepthought]]
arch = "x86_64"
git-tree-sha1 = "393ccafd8ec45ffc3a43c1c8dc648e39782d3fdb"
libc = "musl"
os = "linux"

    [[GAP_pkg_deepthought.download]]
    sha256 = "7a66708bce2296131bbee18222ee783fcd1da2a03ee9dff84a7aa7a715f80524"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v100.0.700+0/GAP_pkg_deepthought.v100.0.700.x86_64-linux-musl.tar.gz"
[[GAP_pkg_deepthought]]
arch = "x86_64"
git-tree-sha1 = "7a2a1c85a2bd076739447cedc89b9696ce865194"
os = "freebsd"

    [[GAP_pkg_deepthought.download]]
    sha256 = "5b54ccc89af6fd23684f5830116db69099ce822b5826895b19c7e8e1de013e86"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v100.0.700+0/GAP_pkg_deepthought.v100.0.700.x86_64-unknown-freebsd.tar.gz"
