[[GAP_pkg_deepthought]]
arch = "aarch64"
git-tree-sha1 = "a69b12caf37fa465a8792240953e393692780276"
os = "macos"

    [[GAP_pkg_deepthought.download]]
    sha256 = "f4a8058c245bd47a7d221df57e5905a98d340cd8967a1d1e06038d1e8ed2af72"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v100.0.702+0/GAP_pkg_deepthought.v100.0.702.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_deepthought]]
arch = "aarch64"
git-tree-sha1 = "4cbf126b4077773150ab816dd45d6202793231ad"
libc = "glibc"
os = "linux"

    [[GAP_pkg_deepthought.download]]
    sha256 = "d9c0298d7e954b57fde87189c5ffb88572707aee0566bb5caabecb4f3e110e86"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v100.0.702+0/GAP_pkg_deepthought.v100.0.702.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_deepthought]]
arch = "aarch64"
git-tree-sha1 = "0198511b07c81989244eaf2218aee59633c1f1c5"
libc = "musl"
os = "linux"

    [[GAP_pkg_deepthought.download]]
    sha256 = "a546dda3a64ab85c0a7a46a3fcd620e80a36b92ee14b84ec2120d757ecc2d98e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v100.0.702+0/GAP_pkg_deepthought.v100.0.702.aarch64-linux-musl.tar.gz"
[[GAP_pkg_deepthought]]
arch = "aarch64"
git-tree-sha1 = "f3122760a9ccd6e45e4c104ce20689901bded40b"
os = "freebsd"

    [[GAP_pkg_deepthought.download]]
    sha256 = "90d594633ef382167e23128302e29f4217b8a5333be01ab36d4a33cf0d9764d6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v100.0.702+0/GAP_pkg_deepthought.v100.0.702.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_deepthought]]
arch = "powerpc64le"
git-tree-sha1 = "06974cf494730d69935896a7fd41b1ed7a56ceee"
libc = "glibc"
os = "linux"

    [[GAP_pkg_deepthought.download]]
    sha256 = "7df9dca903c56186d2a39b126c1720bf28588b84fd9dba7133dc6e33d272701e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v100.0.702+0/GAP_pkg_deepthought.v100.0.702.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_deepthought]]
arch = "riscv64"
git-tree-sha1 = "0a3888818698d856cbf764abfb0fc91354819b85"
libc = "glibc"
os = "linux"

    [[GAP_pkg_deepthought.download]]
    sha256 = "c51a6e81f29d7cb4856071fdc832806967e615257af9b4266c57d6822df0f7c4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v100.0.702+0/GAP_pkg_deepthought.v100.0.702.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_deepthought]]
arch = "x86_64"
git-tree-sha1 = "c4f9e49aa96940254e8dfaa9d526c58761c33222"
os = "macos"

    [[GAP_pkg_deepthought.download]]
    sha256 = "975c5dd1100fadf7530fe639a59cb4719f167f46c484bfe1866a47ee064200d7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v100.0.702+0/GAP_pkg_deepthought.v100.0.702.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_deepthought]]
arch = "x86_64"
git-tree-sha1 = "db240c9e32ae3e033790ad2470b3f2ac89022466"
libc = "glibc"
os = "linux"

    [[GAP_pkg_deepthought.download]]
    sha256 = "e0c2309ea65ad078630ead457d4408bddb5d866844430bb6bb399779f951a0b3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v100.0.702+0/GAP_pkg_deepthought.v100.0.702.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_deepthought]]
arch = "x86_64"
git-tree-sha1 = "bde6307492441f7499dfa2486778f1737c70009a"
libc = "musl"
os = "linux"

    [[GAP_pkg_deepthought.download]]
    sha256 = "05f655b5a118c5aca7defb12a632ae25f7b3be5ad339e54022279641adccdca7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v100.0.702+0/GAP_pkg_deepthought.v100.0.702.x86_64-linux-musl.tar.gz"
[[GAP_pkg_deepthought]]
arch = "x86_64"
git-tree-sha1 = "d0fee84d9a37ffcbc07187fc004a99e4cbb0dce5"
os = "freebsd"

    [[GAP_pkg_deepthought.download]]
    sha256 = "bd2053c86afc47f2b3bfc6950d4a16c408aa23806e18b3d446b884d7fd25d88f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v100.0.702+0/GAP_pkg_deepthought.v100.0.702.x86_64-unknown-freebsd.tar.gz"
