[[GAP_pkg_deepthought]]
arch = "aarch64"
git-tree-sha1 = "05bd2e2f9685d02c428f7c92135ea9856a4cabf8"
os = "macos"

    [[GAP_pkg_deepthought.download]]
    sha256 = "cf4a8d46d76b19a3a979f694f676a5d60ad09e7859a44b15e916771dd31c9cde"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.900.0+0/GAP_pkg_deepthought.v101.900.0.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_deepthought]]
arch = "aarch64"
git-tree-sha1 = "84f0a9593f67a9b943da0877050d8846ea85d5ae"
libc = "glibc"
os = "linux"

    [[GAP_pkg_deepthought.download]]
    sha256 = "b86c7be20f7752871b5bde21e7007ebe2581692085e854d11d7badad8d1dd1fe"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.900.0+0/GAP_pkg_deepthought.v101.900.0.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_deepthought]]
arch = "aarch64"
git-tree-sha1 = "971d16faf38dfc3f40187186590540b96941dfa1"
libc = "musl"
os = "linux"

    [[GAP_pkg_deepthought.download]]
    sha256 = "6021f2f089506501863a45a383b671f7439dee8c4feb5580fee179e017032d3a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.900.0+0/GAP_pkg_deepthought.v101.900.0.aarch64-linux-musl.tar.gz"
[[GAP_pkg_deepthought]]
arch = "aarch64"
git-tree-sha1 = "0ce0f10e207dc51bd7bcad0ed220233f9a7bde9d"
os = "freebsd"

    [[GAP_pkg_deepthought.download]]
    sha256 = "03c8fae1cb2408b58dc6185f5e5efcf5a8e778b13579317b9b1b8e7ce972c6a7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.900.0+0/GAP_pkg_deepthought.v101.900.0.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_deepthought]]
arch = "powerpc64le"
git-tree-sha1 = "3f8a6eb8ba096790ef84ead21aca857711a64236"
libc = "glibc"
os = "linux"

    [[GAP_pkg_deepthought.download]]
    sha256 = "a215aff7e6206e112de347300a8acdffa2a8e793fcd10e7980898486394deb4f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.900.0+0/GAP_pkg_deepthought.v101.900.0.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_deepthought]]
arch = "riscv64"
git-tree-sha1 = "f426285855ea1cd40d9883833943415090648093"
libc = "glibc"
os = "linux"

    [[GAP_pkg_deepthought.download]]
    sha256 = "b1f530138e930e4dd96f1f05626c4c42922ceb3f16940f0df74de6894db09abb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.900.0+0/GAP_pkg_deepthought.v101.900.0.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_deepthought]]
arch = "x86_64"
git-tree-sha1 = "e5bf475b5ec2f446aafea35d08868be55a8af595"
os = "macos"

    [[GAP_pkg_deepthought.download]]
    sha256 = "2c53987d0e131cc33d04bdd44e3599796d5be0ffad7aee3cb1e4d91cff09ee1f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.900.0+0/GAP_pkg_deepthought.v101.900.0.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_deepthought]]
arch = "x86_64"
git-tree-sha1 = "df326859501bc7da40175b9825201d0a0afdaaf6"
libc = "glibc"
os = "linux"

    [[GAP_pkg_deepthought.download]]
    sha256 = "5c5d58b6ef1a2c26c2dc112887ffcf8d3139579ec8dd7dab588679ed6f8711aa"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.900.0+0/GAP_pkg_deepthought.v101.900.0.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_deepthought]]
arch = "x86_64"
git-tree-sha1 = "019d14f92c2cb611db8aa39f100e6999382f72b0"
libc = "musl"
os = "linux"

    [[GAP_pkg_deepthought.download]]
    sha256 = "5ebb05863b256101a81dabe8d0209e4d5088bc1c98386a0a3a84c3bbc41cf0f1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.900.0+0/GAP_pkg_deepthought.v101.900.0.x86_64-linux-musl.tar.gz"
[[GAP_pkg_deepthought]]
arch = "x86_64"
git-tree-sha1 = "b90b7901190f8a6c8f171fcb062bb5832dc20e96"
os = "freebsd"

    [[GAP_pkg_deepthought.download]]
    sha256 = "3d031e1b10db7bcf5493e61acddcafe329fc09f9b337e850da8583ffe4137a33"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.900.0+0/GAP_pkg_deepthought.v101.900.0.x86_64-unknown-freebsd.tar.gz"
